### ISSUE TITLE
Screenshots in README.md

### ISSUE THREAD

**Issue by mkwork** [VolkMilit/CuteMail#19]
It can help to project development. There are no any reason even try to build that without, while there are to much risk to take eye bleeding, again.

Also, its quite easy to insert some current screenshots in relative project directory and update them when new feature done or just time to time. Some projects have practice to take screenshot and publish it's on each new ui feature to demonstrate it. This is only way to get the community in 2k18, neither good or bad you soulution:)

**Comment by VolkMilit** [comment]
Perhaps you're right, I, maybe take some shots, when publish next, 0.3 version. For now I'm trying to redesign some things, so I think it's useless to take screenshots right now.
