### ISSUE TITLE
Get rid of mimetic

### ISSUE THREAD

**Issue by VolkMilit** [VolkMilit/CuteMail#21]
I figure that I doesn't use it that much in code. Besides it's complicated, std implementation that doesn't fit in Qt standarts: I have not very good experience converting std::string in QString. Also there is so match code in it, that CuteMail never be using and I suppose I need just parse eml with bare Qt.
There is one problem, by the way: I still need to decode quoted-printable.

Some todo list:
- [x] Find body in eml (remember, there is can be broken multipart message)
- [x] Parse fields in headers
- [x] Find decode (both ways, from headers and from boundary)

Find replacement for decode:
- [x] base64 (smooth decode with bare Qt)
- [x] QP ~~, I only found this one https://github.com/bluetiger9/Qt-Quoted-Printable, need to check it~~

I have an idea: what about to store parse message in cache file? I'm almost parse header and body, so it's will be not so hard, I suppose.

**Comment by probonopd** [comment]
Still getting an error related to it on the `master` branch:

```
FreeBSD% freebsd-version 
13.0-RELEASE-p5

git clone https://github.com/VolkMilit/CuteMail
cd CuteMail
sudo pkg install libetpan
qmake-qt5
make

In file included from main.cpp:19:
In file included from ./ui/mainwindow.h:40:
In file included from ./core/emlparser.h:31:
./utils/utils.h:25:10: fatal error: 'mimetic/mimetic.h' file not found
#include <mimetic/mimetic.h>
         ^~~~~~~~~~~~~~~~~~~
1 error generated.                                                                               
*** Error code 1

Stop.
make[1]: stopped in /tmp/CuteMail/src
*** Error code 1

Stop.
make: stopped in /tmp/CuteMail
```

This does not happen on the `next` branch.

**Comment by VolkMilit** [comment]
See https://github.com/VolkMilit/CuteMail/issues/35#issuecomment-1003856417
