### ISSUE TITLE
Logo design for CuteMail

### ISSUE THREAD

**Issue by baranpirincal** [VolkMilit/CuteMail#27]
Hello, I am suffering too when I use mail applications because of that I want to support your project by doing logo design. If you are interested, I expect your feedback. Have a nice day :)

Best Regards,
Baran Pirincal
Visual Communication Designer

**Comment by VolkMilit** [comment]
@baranpirincal, hello, yes I will appreciate if you design logo for CuteMail and I can focus on more valuable things :)

**Comment by baranpirincal** [comment]
Hello again, I designed a "cute" logo for "cutemail" :) If it is so cute, we can add or change something on design if you want.  I waiting your feedbacks for sending .png and editable version of logo design. Good night! :)

![cutemail55](https://user-images.githubusercontent.com/37786733/38784704-b5e8f108-411e-11e8-9eea-c08110ecf974.jpg)

![cutemailmockup](https://user-images.githubusercontent.com/37786733/38784714-d0988928-411e-11e8-9201-c2a81078e608.jpg)


![cutemailmockup2](https://user-images.githubusercontent.com/37786733/38784707-bbcd1d10-411e-11e8-896d-254536b0ae79.jpg)

**Comment by VolkMilit** [comment]
@baranpirincal 
Hello. Thank you for contribution it's really pretty looking :)
About design: it's nice, but I'm not fan of material-design. I don't know how to explain it with my poor english, but I can add image.

![this one](https://i.imgur.com/EkA5N6S.png)

Is this necessary for design purposes? I mean, I'm a bit of perfectionist. Except this I like the design in general.
And yes, I don't know why, but I like this color, and I suppose we will use it in future for app icon.

**Comment by baranpirincal** [comment]
In my opinion except the certain rules, logo design does not have many rules. I mean that things you wanted to change are relevant to the choice. Also I  understood you. Here, I made it as you wanted. 
If you do not want another change, I will send you all of these files with .png format and editable .pdf version. Maybe you can decide another color version of logo design in the future :)

![cutemailadamin istedgi](https://user-images.githubusercontent.com/37786733/38794191-e6bfd970-415c-11e8-84d9-b5f2486446f5.jpg)

**Comment by mkwork** [comment]
May be I wrong. But most successful communication applications are using blue palette in the taskbar. It's just observation.

Check it out for example:
* skype
* thunderbird
* outlook
* telegram

**Comment by VolkMilit** [comment]
@baranpirincal, yep, nice. @Shatur95 also suggested make outline thinner, if you don't mind.

@mkwork, well, I don't know. Why everything blue? Perhaps we can make all the colors user like with just svg. For example Firefox icon is mostly #EC8840 but also have some #4AAAE3. I think we can use #F1B55B for logo and something like #0A99ED for icon. Also, email client communication application? Well, in some way, yes, but still, it's not messenger. And again, for example in icon set I using (Vimix), Claws mail have #FECD38 as primary color and white as secondary.
BTW I hear that blue specter is not healthy for eyes ;) That's why your eyes is get tired so quickly close to the monitor.

**Comment by baranpirincal** [comment]
@mkwork I will make blue version as soon as possible, it can be good to see all alternatives before the decision :)

@VolkMilit I will make outline thinner and use color palette which you gave as soon as possible.

**Comment by VolkMilit** [comment]
@baranpirincal, I'm still think we must make logo with some warm colors, so beige\sand\#FABA60\whatever is nice. Also how I would not like blue colors in general, I will listen @mkwork, we also need logo with something like #62C6FF. And then we decide. 
BTW Green and gray is nice too, but red and magenta is far too "flashy".

**Comment by baranpirincal** [comment]
@VolkMilit @mkwork @Shatur95  Hello, I made a blue and thinner outlined version as you wish could you please look it? Have a nice day guys:)

![cutemailson](https://user-images.githubusercontent.com/37786733/38876074-6b5d2c2a-4264-11e8-8f74-c360ed0603d8.jpg)

**Comment by Shatur** [comment]
@baranpirincal, thank you, awesome work! Thin version looks better :)

**Comment by VolkMilit** [comment]
@baranpirincal, perfect. I even think now, that blue is nice for logo. Can you upload editable version and png now? I think we done here. And, again, thank you for contribution :)

**Comment by mkwork** [comment]
@baranpirincal, Thank you! It looks pretty good. I like the bottom one much.

**Comment by baranpirincal** [comment]
@Shatur95 @VolkMilit @mkwork You're welcome guys! I uploaded editable and .PNG format of the logo design. Good luck!

**Comment by VolkMilit** [comment]
@baranpirincal, one more thing: I'm suggesting using Creative Commons license for your art instead of MIT. MIT license is more for software, Creative Commons is more for art. It's just suggesting, maybe you have good reasons to use MIT.
