### ISSUE TITLE
How to add an account

### ISSUE THREAD

**Issue by N1coc4colA** [VolkMilit/CuteMail#33]
Hello, I was looking for some libraries (a long story) and I fell on this app. Now, I compiled it but I have a problem #1st:
QSqlDatabasePrivate::addDatabase: duplicate connection name 'qt_sql_default_connection', old connection removed.
#2nd: How can I add an account? I think it's a bug, your mail app show me the folders of my computer in the email adress list and I can't connect an account, so... I tried a lot... but I havent the response. can you help me please?

**Comment by VolkMilit** [comment]
I'm not touched this code about year now, I don't think it works as expected and works in first place. It need to be rewritten, to be honest, but I don't have much time.

**Comment by N1coc4colA** [comment]
Ok, thanks for the answer. :)
