### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by N1coc4colA** [VolkMilit/CuteMail#34]
Hello, I haven't find a lot of projects which support the mail receiving. I already contact you before. I want to know how did you do to implement the POP3 system. I haven't found a lot of articles and templates of it to implement it in mine.... Can you help me or/and reply me on:
https://github.com/N1coc4colA/mails

**Comment by VolkMilit** [comment]
@N1coc4colA I'm using libetpan for this. But here is downsides: it's written in pure C. AFAIK POP3 is in history now, so I don't think you will find alternative. I have found some KDE libs -- wrapper for IMAP, but I have no time to check them.

**Comment by N1coc4colA** [comment]
Ok, but if you have some times, come see my project, I have a library now: Chilkat. Thanks for answer me :)
